In [6]:
import numpy as np

1. Consider the matrices you encountered in the written test:



$
A = \begin{bmatrix}
0 & 7 & 7 \\
2 & 9 & 1
\end{bmatrix}
$,
$
B = \begin{bmatrix}
1 & 5 \\
3 & 6
\end{bmatrix} 
$

Calculate $BA$, $A^TB$, $B^TA$ using NumPy 

In [9]:
a = np.array([[0, 7, 7], [2, 9, 1]])
b = np.array([[1, 5], [3, 6]])

print(np.matmul(b, a))

array([[10, 52, 12],
       [12, 75, 27]])

In [10]:
a_T = np.transpose(a)
print(np.matmul(a_T, b))

array([[ 6, 12],
       [34, 89],
       [10, 41]])

In [11]:
b_T = np.transpose(b)
print(np.matmul(b_T, a))

array([[ 6, 34, 10],
       [12, 89, 41]])

2. Consider the matrix
$
A = \begin{bmatrix}
3 & 0 & 6 & 2 \\
4 & 7 & 0 & 0 \\
3 & 6 & 9 & 12\\
2 & 4 & 6 & 8
\end{bmatrix}
$, calculate $\det(A)$ using NumPy. Does the inverse exist? If so, calculate it using NumPy.

In [12]:
A = np.array([[3, 0, 6, 2], [4, 7, 0, 0], [3, 6, 9, 12], [2, 4, 6, 8]])
print(np.linalg.det(A))

-1.5102205200686817e-13

In [14]:
# Since determinant is basically 0, therefore no inverse
print(np.linalg.inv(A)) # if there is an inverse, this is how to calculate

[[ 3.04347826e-01  1.73913043e-01  1.66863049e+15 -2.50294573e+15]
 [-1.73913043e-01  4.34782609e-02 -9.53503135e+14  1.43025470e+15]
 [ 1.44927536e-02 -8.69565217e-02 -1.13890652e+15  1.70835978e+15]
 [-0.00000000e+00 -0.00000000e+00  9.13773837e+14 -1.37066076e+15]]


3. Consider the matrix
$
B = \begin{bmatrix}
3 & 0 & 6 & 2 \\
4 & 7 & 0 & 0 \\
3 & 6 & 9 & 12\\
2 & 4 & 6 & 9
\end{bmatrix}
$, calculate $\det(B)$ using NumPy. Does the inverse exist? If so, calculate it using NumPy.

In [15]:
B = np.array([[3, 0, 6, 2], [4, 7, 0, 0], [3, 6, 9, 12], [2, 4, 6, 9]])
print(np.linalg.det(B))

206.99999999999994


In [16]:
print(np.linalg.inv(B))

[[ 0.30434783  0.17391304 -1.42028986  1.82608696]
 [-0.17391304  0.04347826  0.8115942  -1.04347826]
 [ 0.01449275 -0.08695652  0.93236715 -1.24637681]
 [ 0.          0.         -0.66666667  1.        ]]
