In [6]:
import numpy as np
import matplotlib.pyplot as plt
from scipy import signal

In [7]:
# Create the image
input_img = np.arange(1,17,1)
input_img = input_img.reshape(4,4)

# Create the Kernel
kernel  = np.array([[1,0,-1],[2,0,-2],[1,0,-1]])

input_img

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [15]:
kernel

array([[ 1,  0, -1],
       [ 2,  0, -2],
       [ 1,  0, -1]])

In [13]:
signal.convolve2d(input_img, kernel, "same")

array([[ 10,   6,   6, -13],
       [ 24,   8,   8, -28],
       [ 40,   8,   8, -44],
       [ 38,   6,   6, -41]])

In [51]:
# Convolution done only using numpy
def myConvolution(img, kernel, padding):
	offset = 1
	if padding:
		# https://stackoverflow.com/questions/35751306/python-how-to-pad-numpy-array-with-zeros
		# Refer to above explanation, but basically the array is the padding for each dimension
		img = np.pad(img, [(1, 1), (1, 1)], mode='constant')
		offset = 2 # offset for convolution answer (if padding, subtract more)

	flipped_kernel = np.rot90(kernel, k=2) # Flip kernel for convolution (automatically done by function usually)
	k_dim = flipped_kernel.shape[0] # square, so doesn't matter

	rows, cols = img.shape
	convoluted_img = np.zeros((rows - offset, cols - offset), dtype=int) # defining answer array with 0s
	for i in range(cols - offset):
		for j in range(rows - offset):
			extracted_img = img[i:i+k_dim, j:j+k_dim] # extract nxn around pixel
			multiplied = extracted_img * flipped_kernel # multiply pixel nxn and kernel together
			convoluted_img[i][j] = sum(multiplied.flatten()) # summing all elements in array

	return convoluted_img


In [52]:
print(myConvolution(input_img, kernel, True))

[[ 10   6   6 -13]
 [ 24   8   8 -28]
 [ 40   8   8 -44]
 [ 38   6   6 -41]]


In [53]:
def checkConvolution(img, kernel, padding=True):
	if padding:
		proper = signal.convolve2d(img, kernel, "same")
	else:
		proper = signal.convolve2d(img, kernel, "valid")
		
	mine = myConvolution(img, kernel, padding)
	
	print(np.array_equal(proper, mine))
	print(mine)

checkConvolution(input_img, kernel)

True
[[ 10   6   6 -13]
 [ 24   8   8 -28]
 [ 40   8   8 -44]
 [ 38   6   6 -41]]


In [55]:
# Exercise 5: complete convolution by hand and check with above function
test_img = np.array([1, 0, -2, 1, -1, 0, 1, 2, 0, 2, 1, 0, 1, 0, 0, 1])
test_img = test_img.reshape(4, 4)
test_kernel = np.array([2, -1, 1, 0])
test_kernel = test_kernel.reshape(2, 2)

checkConvolution(test_img, test_kernel, padding=False)

True
[[1 0 4]
 [4 1 1]
 [1 1 2]]
